chore(deps): Bump kotlinVersion from 1.5.0 to 1.5.10 (#134)
Bumps `kotlinVersion` from 1.5.0 to 1.5.10.
Updates `kotlin-stdlib-jdk8` from 1.5.0 to 1.5.10
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/JetBrains/kotlin/releases">kotlin-stdlib-jdk8's releases</a>.</em></p>
<blockquote>
<h2>Kotlin 1.5.10</h2>
<h4><a href="https://kotlinlang.org/docs/releases.html#update-to-a-new-release">How to update to a new release</a></h4>
<h2>Changelog</h2>
<h3>Compiler</h3>
<h4>Fixes</h4>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-41078"><code>KT-41078</code></a> Incorrect type substitution in contracts with type parameters</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-44770"><code>KT-44770</code></a> JVM / IR: &quot;IllegalArgumentException: Unrecognized Type: [null]&quot; Jackson doesn't recognize type</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-45084"><code>KT-45084</code></a> JVM IR: &quot;NoSuchElementException: Sequence contains no element matching the predicate&quot; when inline class is passed to lambda with &gt;22 parameters</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-45779"><code>KT-45779</code></a> JVM / IR: java.lang.NoSuchMethodError: 'int java.lang.Integer.plus(int)' caused by function reference</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-45941"><code>KT-45941</code></a> JVM IR: local functions use generic type parameters of the outer class in the bytecode, which breaks Bytebuddy and MockK</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46149"><code>KT-46149</code></a> Generate synthetic classes for SAM adapters with erased instead of generic supertype</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46189"><code>KT-46189</code></a> JVM IR: tailrec function with capturing lambda in default parameter value leads to NoSuchMethodError at runtime</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46214"><code>KT-46214</code></a> JVM / IR: &quot;IllegalStateException: No mapping for symbol: VALUE_PARAMETER INSTANCE_RECEIVER&quot; on a suspend function in an inner class</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46238"><code>KT-46238</code></a> JVM IR: BootstrapMethodError in JDK 11+ on intersection type passed in arguments of SAM adapter where SAM interface's type parameter has a non-trivial upper bound</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46259"><code>KT-46259</code></a> JVM IR: local function for adapted function reference is not declared as ACC_SYNTHETIC</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46284"><code>KT-46284</code></a> JVM IR: &quot;Unbound private symbol IrClassSymbol&quot; on class reference to script class</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46402"><code>KT-46402</code></a> IllegalAccessError: &quot;CapturedLambdaInterpreter (in unnamed module <a href="https://github.com/0x71b06418"><code>@​0x71b06418</code></a>) cannot access class jdk.internal.org.objectweb.asm.Type&quot; caused by inline function with a suspend parameter in Maven project</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46408"><code>KT-46408</code></a> JVM IR: BootstrapMethodError due to missing bridge for subclass of generic Java interface</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46426"><code>KT-46426</code></a> JVM IR: Corrupted .class file when passing Array constructor reference as (inline) lambda</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46455"><code>KT-46455</code></a> OOM on parsing invalid code with string interpolation</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46503"><code>KT-46503</code></a> JVM IR: &quot;AssertionError: Unexpected variance in super type argument: out <a href="https://github.com/1"><code>@​1</code></a>&quot;</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46505"><code>KT-46505</code></a> JVM IR: NullPointerException caused by a callable reference with nullable inline value class parameter</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46512"><code>KT-46512</code></a> JVM / IR: NoSuchMethodError on SAM conversion of a function reference</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46515"><code>KT-46515</code></a> IndexOutOfBoundsException: &quot;Empty list doesn't contain element at index 0.&quot; on bad variable name in 1.5.0</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46516"><code>KT-46516</code></a> JVM IR: &quot;AnalyzerException: Expected I, but found R&quot; on subclassing AbstractMutableList<!-- raw HTML omitted --></li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46524"><code>KT-46524</code></a> Cannot use unsigned literals with api-version &lt; 1.5 even with opt-in</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46537"><code>KT-46537</code></a> JVM / IR: &quot;IllegalStateException: No noarg super constructor for CLASS&quot; caused by &quot;No-arg&quot; plugin with annotation on child class</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46540"><code>KT-46540</code></a> JVM / IR: AnalyzerException: Expected an object reference, but found J caused by java.function.Supplier</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46554"><code>KT-46554</code></a> JVM IR: &quot;IllegalStateException: No mapping for symbol: VAR IR_TEMPORARY_VARIABLE&quot; with value class constructor delegation call</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46555"><code>KT-46555</code></a> JVM IR: IllegalAccessError when using Java method reference</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46562"><code>KT-46562</code></a> Kotlin 1.5.0 generates non-serializable lambdas when they should be serializable</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46568"><code>KT-46568</code></a> JVM IR: &quot;AssertionError: IrCall expected inside JvmStatic wrapper&quot; on compiling protected static function with return type Nothing inside companion object of abstract class</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46574"><code>KT-46574</code></a> JVM / IR: ClassCastException caused by runBlocking awaiting call while returning Kotlin.Result type.</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46579"><code>KT-46579</code></a> JVM IR: &quot;IllegalArgumentException: Sequence contains more than one matching element&quot; for Java enum with overloaded values() static method</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46584"><code>KT-46584</code></a> JVM IR: Intrinsics.needClassReification (UnsupportedOperationException thrown). Property delegate provider crossinline lambda inlining/reification issue</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46751"><code>KT-46751</code></a> JVM / IR:&quot;ClassCastException: java.lang.String cannot be cast to java.lang.Void&quot; in extension function in Kotlin 1.5</li>
</ul>
<h3>IDE</h3>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-45981"><code>KT-45981</code></a> failed to analyze: java.lang.AssertionError: diagnostic callback has been already registered: Code analysis get stuck in AS 2020.3.1.14 &amp; Kotlin v1.5.0-M2</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46622"><code>KT-46622</code></a> 60+ second freezes with Kotlin plugin 1.5.0: GetModuleInfoKt.findJvmStdlibAcrossDependencies</li>
</ul>
<h3>IDE. Gradle Integration</h3>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46417"><code>KT-46417</code></a> [UNRESOLVED_REFERENCE] For project to project dependencies of native platform test source sets</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a href="https://github.com/JetBrains/kotlin/blob/master/ChangeLog.md">kotlin-stdlib-jdk8's changelog</a>.</em></p>
<blockquote>
<h2>1.5.10</h2>
<h3>Compiler</h3>
<h4>Fixes</h4>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-41078"><code>KT-41078</code></a> Incorrect type substitution in contracts with type parameters</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-44770"><code>KT-44770</code></a> JVM / IR: &quot;IllegalArgumentException: Unrecognized Type: [null]&quot; Jackson doesn't recognize type</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-45084"><code>KT-45084</code></a> JVM IR: &quot;NoSuchElementException: Sequence contains no element matching the predicate&quot; when inline class is passed to lambda with &gt;22 parameters</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-45779"><code>KT-45779</code></a> JVM / IR: java.lang.NoSuchMethodError: 'int java.lang.Integer.plus(int)' caused by function reference</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-45941"><code>KT-45941</code></a> JVM IR: local functions use generic type parameters of the outer class in the bytecode, which breaks Bytebuddy and MockK</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46149"><code>KT-46149</code></a> Generate synthetic classes for SAM adapters with erased instead of generic supertype</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46189"><code>KT-46189</code></a> JVM IR: tailrec function with capturing lambda in default parameter value leads to NoSuchMethodError at runtime</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46214"><code>KT-46214</code></a> JVM / IR: &quot;IllegalStateException: No mapping for symbol: VALUE_PARAMETER INSTANCE_RECEIVER&quot; on a suspend function in an inner class</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46238"><code>KT-46238</code></a> JVM IR: BootstrapMethodError in JDK 11+ on intersection type passed in arguments of SAM adapter where SAM interface's type parameter has a non-trivial upper bound</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46259"><code>KT-46259</code></a> JVM IR: local function for adapted function reference is not declared as ACC_SYNTHETIC</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46284"><code>KT-46284</code></a> JVM IR: &quot;Unbound private symbol IrClassSymbol&quot; on class reference to script class</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46402"><code>KT-46402</code></a> IllegalAccessError: &quot;CapturedLambdaInterpreter (in unnamed module <a href="https://github.com/0x71b06418"><code>@​0x71b06418</code></a>) cannot access class jdk.internal.org.objectweb.asm.Type&quot; caused by inline function with a suspend parameter in Maven project</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46408"><code>KT-46408</code></a> JVM IR: BootstrapMethodError due to missing bridge for subclass of generic Java interface</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46426"><code>KT-46426</code></a> JVM IR: Corrupted .class file when passing Array constructor reference as (inline) lambda</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46455"><code>KT-46455</code></a> OOM on parsing invalid code with string interpolation</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46503"><code>KT-46503</code></a> JVM IR: &quot;AssertionError: Unexpected variance in super type argument: out <a href="https://github.com/1"><code>@​1</code></a>&quot;</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46505"><code>KT-46505</code></a> JVM IR: NullPointerException caused by a callable reference with nullable inline value class parameter</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46512"><code>KT-46512</code></a> JVM / IR: NoSuchMethodError on SAM conversion of a function reference</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46515"><code>KT-46515</code></a> IndexOutOfBoundsException: &quot;Empty list doesn't contain element at index 0.&quot; on bad variable name in 1.5.0</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46516"><code>KT-46516</code></a> JVM IR: &quot;AnalyzerException: Expected I, but found R&quot; on subclassing AbstractMutableList<!-- raw HTML omitted --></li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46524"><code>KT-46524</code></a> Cannot use unsigned literals with api-version &lt; 1.5 even with opt-in</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46537"><code>KT-46537</code></a> JVM / IR: &quot;IllegalStateException: No noarg super constructor for CLASS&quot; caused by &quot;No-arg&quot; plugin with annotation on child class</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46540"><code>KT-46540</code></a> JVM / IR: AnalyzerException: Expected an object reference, but found J caused by java.function.Supplier</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46554"><code>KT-46554</code></a> JVM IR: &quot;IllegalStateException: No mapping for symbol: VAR IR_TEMPORARY_VARIABLE&quot; with value class constructor delegation call</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46555"><code>KT-46555</code></a> JVM IR: IllegalAccessError when using Java method reference</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46562"><code>KT-46562</code></a> Kotlin 1.5.0 generates non-serializable lambdas when they should be serializable</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46568"><code>KT-46568</code></a> JVM IR: &quot;AssertionError: IrCall expected inside JvmStatic wrapper&quot; on compiling protected static function with return type Nothing inside companion object of abstract class</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46574"><code>KT-46574</code></a> JVM / IR: ClassCastException caused by runBlocking awaiting call while returning Kotlin.Result type.</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46579"><code>KT-46579</code></a> JVM IR: &quot;IllegalArgumentException: Sequence contains more than one matching element&quot; for Java enum with overloaded values() static method</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46584"><code>KT-46584</code></a> JVM IR: Intrinsics.needClassReification (UnsupportedOperationException thrown). Property delegate provider crossinline lambda inlining/reification issue</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46751"><code>KT-46751</code></a> JVM / IR:&quot;ClassCastException: java.lang.String cannot be cast to java.lang.Void&quot; in extension function in Kotlin 1.5</li>
</ul>
<h3>IDE</h3>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-45981"><code>KT-45981</code></a> failed to analyze: java.lang.AssertionError: diagnostic callback has been already registered: Code analysis get stuck in AS 2020.3.1.14 &amp; Kotlin v1.5.0-M2</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46622"><code>KT-46622</code></a> 60+ second freezes with Kotlin plugin 1.5.0: GetModuleInfoKt.findJvmStdlibAcrossDependencies</li>
</ul>
<h3>IDE. Gradle Integration</h3>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46417"><code>KT-46417</code></a> [UNRESOLVED_REFERENCE] For project to project dependencies of native platform test source sets</li>
</ul>
<h3>Libraries</h3>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-46280"><code>KT-46280</code></a> JvmRecord annotation missing constructor in common</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/JetBrains/kotlin/commit/5af81b4373c410b4e9920822c2ded02903d351eb"><code>5af81b4</code></a> Update Kotlin/Native: 1.5.10-release-76</li>
<li><a href="https://github.com/JetBrains/kotlin/commit/b3134c0232c22b81e62f1e33ab1082564408c913"><code>b3134c0</code></a> Implemented collecting use-old-backend flag from Gradle</li>
<li><a href="https://github.com/JetBrains/kotlin/commit/0505d58c54871a8c2ffac446ab3bc90a4a1195d3"><code>0505d58</code></a> Fix exposing provided by Gradle Kotlin dependencies.</li>
<li><a href="https://github.com/JetBrains/kotlin/commit/f0f2b92b4e3237dce967946492352661a7d5ce3f"><code>f0f2b92</code></a> Parcelize: Handle class hierarchies of Parcelers (KT-46567)</li>
<li><a href="https://github.com/JetBrains/kotlin/commit/87b2cc158e00ea6ac4715696d0636113e3ea2669"><code>87b2cc1</code></a> IR: Lower shared variables in enum entries (KT-46605)</li>
<li><a href="https://github.com/JetBrains/kotlin/commit/43a81e35d7368476212ac3bce5df85d3b9db7134"><code>43a81e3</code></a> Update Kotlin/Native: 1.5.10-eap-69</li>
<li><a href="https://github.com/JetBrains/kotlin/commit/61cdc669b5edd337581fbbd54d53f8856c9dd600"><code>61cdc66</code></a> Cache all module dependencies to avoid O(n^2) calc complexity</li>
<li><a href="https://github.com/JetBrains/kotlin/commit/40ced5aea0519d47d405d7adb8e389d5f61bd58a"><code>40ced5a</code></a> Do not insert Nothing handling in JvmStatic wrapper.</li>
<li><a href="https://github.com/JetBrains/kotlin/commit/e6966d2c8f73caac707f155a72a41056cd4f2db2"><code>e6966d2</code></a> Revert &quot;JVM IR: mute testJvmStaticAndJvmInline for 1.5.0&quot;</li>
<li><a href="https://github.com/JetBrains/kotlin/commit/8d86066547f0e43476ba51f5c8b17b0f7cff826d"><code>8d86066</code></a> Minor. Make test actually suspend and add a test without suspension</li>
<li>Additional commits viewable in <a href="https://github.com/JetBrains/kotlin/compare/v1.5.0...v1.5.10">compare view</a></li>
</ul>
</details>
<br />

Updates `org.jetbrains.kotlin.jvm` from 1.5.0 to 1.5.10


Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually
- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)


</details>