chore(deps): Bump kotlinVersion from 1.4.10 to 1.4.21 (#91)
Bumps `kotlinVersion` from 1.4.10 to 1.4.21.
Updates `kotlin-stdlib-jdk8` from 1.4.10 to 1.4.21
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/JetBrains/kotlin/releases">kotlin-stdlib-jdk8's releases</a>.</em></p>
<blockquote>
<h2>Kotlin 1.4.21</h2>
<h2>CHANGELOG</h2>
<h3>IDE. Gradle Integration</h3>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-42561"><code>KT-42561</code></a> &quot;Could not get unknown property 'sourceSets' for project&quot; when running JVM module with included MPP module</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-43511"><code>KT-43511</code></a> Task 'MainKt.main()' not found in root project</li>
</ul>
<h3>Libraries</h3>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-43586"><code>KT-43586</code></a> Source documentation:  ExperimentalPathAPI misspelt</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-43745"><code>KT-43745</code></a> <code>replace</code> for strings ignores case of locale characters</li>
</ul>
<h3>Native. C and ObjC Import</h3>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-43265"><code>KT-43265</code></a> Kotlin/Native fails to generate alias for C enum entry</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-43530"><code>KT-43530</code></a> Kotlin/Native compilation fails with &quot;Symbol for public kotlin/Array.size.<!-- raw HTML omitted -->|-8255337774232345969[0] is unbound&quot;</li>
</ul>
<h3>Native</h3>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-43517"><code>KT-43517</code></a> On Kotlin 1.4.20 we got kotlin.NotImplementedError when try compile iOS framework</li>
</ul>
<h3>Tools. Gradle. JS</h3>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-43668"><code>KT-43668</code></a> PackageJson task use file dependencies as is (files and directories), but only files necessary</li>
</ul>
<h2>Checksums</h2>
<table>
<thead>
<tr>
<th>File</th>
<th>Sha256</th>
</tr>
</thead>
<tbody>
<tr>
<td>kotlin-compiler-1.4.21.zip</td>
<td>46720991a716e90bfc0cf3f2c81b2bd735c14f4ea6a5064c488e04fd76e6b6c7</td>
</tr>
<tr>
<td>kotlin-native-linux-1.4.21.tar.gz</td>
<td>140c06ede7d4c23ff65fb8de507aff117e96d8330dbb9b910a730bfb70bca59c</td>
</tr>
<tr>
<td>kotlin-native-macos-1.4.21.tar.gz</td>
<td>e7a13b3138e2769a1ab0b9eb8187b56f8874380cdd96479702f1063ce7de69ca</td>
</tr>
<tr>
<td>kotlin-native-windows-1.4.21.zip</td>
<td>e97242bb79a945f20ebc749200f30b80865b725054b098d9c2dec3e09a98a3d</td>
</tr>
</tbody>
</table>
<h2>Kotlin 1.4.20</h2>
<h2>CHANGELOG</h2>
<h3>Android</h3>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-42121"><code>KT-42121</code></a> Deprecate Kotlin Android Extensions compiler plugin</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-42267"><code>KT-42267</code></a> <code>Platform declaration clash</code> error in IDE when using <code>kotlinx.android.parcel.Parcelize</code></li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-42406"><code>KT-42406</code></a> Long or infinite code analysis on simple files modification</li>
</ul>
<h3>Backend. Native</h3>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-27534"><code>KT-27534</code></a> Bridges to Nothing-returning methods have incorrect signature</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-30284"><code>KT-30284</code></a> Native: Nothing? type for expression override and crash</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-36430"><code>KT-36430</code></a> Optimize when with in range cases</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a href="https://github.com/JetBrains/kotlin/blob/master/ChangeLog.md">kotlin-stdlib-jdk8's changelog</a>.</em></p>
<blockquote>
<h1>CHANGELOG</h1>
<h2>1.4.20</h2>
<h3>Android</h3>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-42121"><code>KT-42121</code></a> Deprecate Kotlin Android Extensions compiler plugin</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-42267"><code>KT-42267</code></a> <code>Platform declaration clash</code> error in IDE when using <code>kotlinx.android.parcel.Parcelize</code></li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-42406"><code>KT-42406</code></a> Long or infinite code analysis on simple files modification</li>
</ul>
<h3>Backend. Native</h3>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-27534"><code>KT-27534</code></a> Bridges to Nothing-returning methods have incorrect signature</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-30284"><code>KT-30284</code></a> Native: Nothing? type for expression override and crash</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-36430"><code>KT-36430</code></a> Optimize when with in range cases</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-38787"><code>KT-38787</code></a> Missing optimization for &quot;in range&quot; check</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-39100"><code>KT-39100</code></a> Make Native behaviour of property initialization consistent with JVM</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-39798"><code>KT-39798</code></a> Override equals/hashCode in functional interface wrappers on Native</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-39800"><code>KT-39800</code></a> equals/hashCode on adapted function references on Native</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-41394"><code>KT-41394</code></a> Compilation failed: Backend Internal error: Exception during IR lowering</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-41907"><code>KT-41907</code></a> Framework test segfaults on GC on watchos_x86 compiled with -opt</li>
</ul>
<h3>Compiler</h3>
<h4>New Features</h4>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-21147"><code>KT-21147</code></a> JEP 280: Indify String Concatenation (StringConcatFactory)</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-34178"><code>KT-34178</code></a> Scripts should be able to access imports objects</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-35549"><code>KT-35549</code></a> Support kotlin-android-extensions in JVM IR backend (for use with Jetpack Compose projects)</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-31567"><code>KT-31567</code></a> Support special semantics for underscore-named catch block parameters</li>
</ul>
<h4>Performance Improvements</h4>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-20571"><code>KT-20571</code></a> Coroutines: Reduce number of local variables stored at suspension point</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-28016"><code>KT-28016</code></a> Coroutine state-machines spill/unspill shall be optimized using data-flow analysis</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-33394"><code>KT-33394</code></a> UI freezes triggered by QualifiedExpressionResolver.resolveToPackageOrClassPrefix</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-36814"><code>KT-36814</code></a> Support optimized delegated properties in JVM_IR</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-36829"><code>KT-36829</code></a> Optimize 'in' expressions (operator fun contains) in JVM_IR</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-41741"><code>KT-41741</code></a> NI: &quot;AssertionError: Empty intersection for types&quot; with generic Java collection</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-42195"><code>KT-42195</code></a> NI: prohibitively long compilation time for values of nested data structures with type inference</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-42221"><code>KT-42221</code></a> Native compiler never finishes frontend phase after migrating to Kotlin 1.4.10</li>
</ul>
<h4>Fixes</h4>
<ul>
<li><a href="https://youtrack.jetbrains.com/issue/KT-11713"><code>KT-11713</code></a> Refine visibility check for synthetic property with protected setter</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-16222"><code>KT-16222</code></a> Coroutine should be clearing any internal state as soon as possible to avoid memory leaks</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-25519"><code>KT-25519</code></a> Extra inline marks inside suspending function callable reference bytecode</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-33226"><code>KT-33226</code></a> Object INSTANCE field not annotated with NotNull in generated bytecode</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-35495"><code>KT-35495</code></a> FIR: forbid non-Java synthetic properties</li>
<li><a href="https://youtrack.jetbrains.com/issue/KT-35651"><code>KT-35651</code></a> Kotlin stdlib has greater resolution priority than jars added via <a href="https://github.com/file">@file</a>:DependsOn annotation</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/JetBrains/kotlin/commit/a3b14561c4d5f2ab5a7edc53fca7d3c891589f2c"><code>a3b1456</code></a> Revert using regex Pattern in String.replace</li>
<li><a href="https://github.com/JetBrains/kotlin/commit/cb93152fed74360a7cb536ed603fe1735e95d6f2"><code>cb93152</code></a> Build: Set file access rights explicitly in kotlin-stdlib-js jar</li>
<li><a href="https://github.com/JetBrains/kotlin/commit/4c44045e9d281e26294fb1ad99f4778a46c57940"><code>4c44045</code></a> Bumped K/N version</li>
<li><a href="https://github.com/JetBrains/kotlin/commit/40abf82dd46ffeecfdf4bbb86a7aaf4657049f02"><code>40abf82</code></a> [Gradle, JS] Add filter on file on fileCollectionDependencies because Gradle ...</li>
<li><a href="https://github.com/JetBrains/kotlin/commit/166ce6a2ea2824c4b990cbbf8a422b89e62b1019"><code>166ce6a</code></a> KTIJ-585 [Gradle Runner]: main() cannot be launched from AS 4.1</li>
<li><a href="https://github.com/JetBrains/kotlin/commit/5e23440a2a552e9bad64ede23e276f42919b6dde"><code>5e23440</code></a> IC &amp; Coroutines: Do not box suspend operator fun invoke receiver</li>
<li><a href="https://github.com/JetBrains/kotlin/commit/0b495c15317a8c3a79223d04fc121018257b8603"><code>0b495c1</code></a> IC &amp; Coroutines: Unbox inline class parameter of suspend lambda</li>
<li><a href="https://github.com/JetBrains/kotlin/commit/a48f76d4d9878a0dd73c9eaac0841df85cde4892"><code>a48f76d</code></a> IC &amp; Coroutines: Unbox inline classes of suspend lambdas</li>
<li><a href="https://github.com/JetBrains/kotlin/commit/a173e0e631cd52e1674bcc91f18c1934df815c1d"><code>a173e0e</code></a> Fix annotation spelling in docs</li>
<li><a href="https://github.com/JetBrains/kotlin/commit/02d925a73bdb34b0d91c8ae9a9a0510e90369e36"><code>02d925a</code></a> Qualify replacement expression with receiver to workaround KT-42874</li>
<li>Additional commits viewable in <a href="https://github.com/JetBrains/kotlin/compare/v1.4.10...v1.4.21">compare view</a></li>
</ul>
</details>
<br />

Updates `org.jetbrains.kotlin.jvm` from 1.4.10 to 1.4.21


Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually
- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)
- `@dependabot badge me` will comment on this PR with code to add a "Dependabot enabled" badge to your readme

Additionally, you can set the following in the `.dependabot/config.yml` file in this repo:
- Update frequency
- Out-of-range updates (receive only lockfile updates, if desired)
- Security updates (receive only security updates, if desired)



</details>